docker:
  version: 1.0
  registry: http://192.168.1.181:2375
  image: ${spring.application.name}:${docker.version}
  tag: 192.168.1.181:5000/frame/${docker.image}
  jar: ${spring.application.name}-${docker.version}

server:
  port: 9902
spring:
  application:
    name: customer
  redis:
    database: 2
    port: 6379
    host: localhost
istio:
  namespace: lvmoney
  docker:
    image:
      tag: ${docker.tag}
      name: ${docker.image}
      pull: Always
    file:
      name: ${docker.jar}
      temp: /home
  yaml:
    cover: true
    replicas: 1
    version: v1
  master:
    ip: 192.168.1.181
rpc:
  server:
    gateway: http://localhost:8888
operating:
  environment: local
  internal: internal