server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: dalaoyang
        uri: http://www.sina.com/
        predicates:
          - Path=/dalaoyang/**
      - id: juejin
        uri: http://www.baidu.com/
        predicates:
          - Path=/juejin/**