server:
  port: 8888
spring:
  application:
    name: gateway-service
  redis:
    database: 4
    port: 6379
    host: 10.20.128.234
  cloud:
    gateway:
      routes:
      - id: dalaoyang
        uri: http://www.sina.com/
        predicates:
          - Path=/dalaoyang/**
      - id: juejin
        uri: http://www.baidu.com/
        predicates:
          - Path=/juejin/**
        filters:
          # 熔断降级配置
          - name: Hystrix
            args:
              name: default
              fallbackUri: forward:/defaultfallback
          # redis限流 ， filter名称必须是RequestRateLimiter
          - name: RequestRateLimiter
            args:
              # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
              key-resolver: '#{@remoteAddrKeyResolver}'
              # 每秒最大访问次数
              redis-rate-limiter.replenishRate: 20
              # 令牌桶最大容量
              redis-rate-limiter.burstCapacity: 20

# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
