docker:
  version: 1.0
  registry: http://192.168.1.181:2375
  image: ${spring.application.name}:${docker.version}
  tag: 192.168.1.181:5000/frame/${docker.image}
  jar: ${spring.application.name}-${docker.version}


server:
  port: 9901
spring:
  application:
    name: provider
  redis:
    database: 2
    port: 6379
    host: localhost
  cloud:
    config:
      label: master
      #对应Config Server所获取的配置文件的{profile}，这里表示获取开发版的配置信息
      profile: dev
      #Config Server的地址
      uri: http://localhost:8974/
istio:
  namespace: lvmoney
  docker:
    image:
      tag: ${docker.tag}
      name: ${docker.image}
      pull: Always
    file:
      name: ${docker.jar}
      temp: /home
  yaml:
    cover: true
    replicas: 1
    version: v2
    destination:
      support: true
      v1: 90
      v2: 10
    mirror:
      support: true
      version: v1
    fault:
      support: true
      percent: 90
      delay: 7
    policy:
      maxConnections: 2048
      connectTimeout: 3s
      http1MaxPendingRequests: 1024
      maxRequestsPerConnection: 200
      http2MaxRequests: 2048
      consecutiveErrors: 3
      maxRetries: 3
      interval: 3s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
  master:
    ip: 192.168.1.181

operating:
  environment: local
  internal: internal