server:
  port: 8800
spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: booszy
  application:
    name: sc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lvmoney/config
          searchPaths: '{application}'
          username: 365619103@qq.com  # 以及相应的账户名
          password: paasssss  # 和密码
  consul:
    host: 127.0.0.1
    port: 8500
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: sc-config-server