spring:
  application:
    name: seata-server
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  cloud:
    alibaba:
      seata:
        tx-service-group: default
  datasource:
    url: jdbc:mysql://10.20.128.234:3306/fescar?useSSL=false&serverTimezone=UTC
    username: scltzhy
    password: scltzhy2019888
server:
  port: 8072
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    io.seata : debug